---

# The mitmdump program handles most backend requests to InfluxDB but
# our proxy code needs to make requests directly so it can cache the
# set of retention polices for each database.
#
# FIXME This same information is held by mitmdump somewhere, since we
# pass it on the command-line, but I don't know how to access it from
# within the proxy script...
influxdb_url: "http://localhost:8086"

# Per-database configurations mapping the 'GROUP BY $interval'
# requested by Grafana to an appropriate InfluxDB retention policy.
#
# Top level entries are InfluxDB database names with corresponding
# mappings.  The _default_ entry will be used for queries with a
# database not explicitly named.
#
# Second-level entries are a list of 2-element lists.  These sublists
# define the a bound and the name of an InfluxDB retention policy.  If
# the 'GROUP BY $interval' requested is larger than the bound, the
# corresponding InfluxDB retention policy will be used.  To ensure the
# smallest such bound is selected, order the list by bound, as in the
# second example below.
rps_by_limit:
  # Example below should remain as the default.
  _default_:
    - [0, "default"]
  # Example below is more complete:
  # my_database:
  #   - [0,     "default"]
  #   - [60,    "1min"]
  #   - [1800,  "5min"]
  #   - [10800, "1hour"]
  #   - [86400, "1day"]
