---

# Produce debugging output during run.
debug: true

# The mitmdump program handles most backend requests to InfluxDB but
# our proxy code needs to make requests directly so it can cache the
# set of retention polices for each database.
#
# FIXME This same information is held by mitmdump somewhere, since we
# pass it on the command-line, but I don't know how to access it from
# within the proxy script...
influxdb_url: "http://localhost:8086"

# Per-database configurations configuration logic for query
# re-writing.
#
# The top-level entry is a map from InfluxDB database names to
# corresponding proxy handling logic.  If no database is specified in
# a query, the '_default_' handling will be used.
#
# The proxy handling logic for each database name is an array of maps
# specifying conditions to select particular retention policies within
# that database.  Each map should contain the following keys:
#
#   * name -- the name of the retention policy to use.
#   
#   * interval -- the smallest GROUP BY interval (in seconds) for
#                 which this retention policy should be selected.
#
#   * retention -- the retention period (in seconds) for this
#                  retention policy.
#    
# If the 'GROUP BY $interval' requested is larger than the 'interval'
# and the query's lookback period is within the 'retention' period,
# the corresponding InfluxDB retention policy 'name' will be used.
#
# To ensure the best retention policy is selected, order the list by
# 'interval', as in the second example below.
#
# To specify an infinite retention period (INF in InfluxDB), use the
# string 'inf', as below.
retention_policies:
  # Example below should remain as the default.
  _default_:
    - name:      "default"
      interval:  0
      retention: "inf"
  # Example below is more complete and serves as a good default for
  # Grafana.
  #
  operations:
    - name:     "for_1d_raw"
      interval: 0
      retention: 3600
    - name:     "for_7d_at_1m"
      interval: 60
      retention: 604800          # 7d
    - name:     "for_90d_at_10m"
      interval: 600
      retention: 7776000         # 90d
    - name:     "forever_at_1h"
      interval: 3600
      retention: 'inf'
